/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ErrorState: typeof import('./src/components/ErrorState.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoadingState: typeof import('./src/components/LoadingState.vue')['default']
    RocketDetail: typeof import('./src/components/RocketDetail.vue')['default']
    RocketTable: typeof import('./src/components/RocketTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
  }
}
